language: python
python:
  - 2.7
  - 3.4
  - 3.6
install:
  - pip install --upgrade pip
  - head -n 12 requirements.txt >test-requirements.txt
  - pip install -r test-requirements.txt --only-binary ':all:'
script:
  - python setup.py test
