language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
sudo: false

install:
  # Install miniconda
  # -----------------
  - >
    echo 'Installing miniconda';
    export CONDA_BASE=https://repo.continuum.io/miniconda/Miniconda;
    if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
      wget --quiet ${CONDA_BASE}2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget --quiet ${CONDA_BASE}3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi;
    bash miniconda.sh -b -p $HOME/miniconda;
    export PATH="$HOME/miniconda/bin:$PATH";
  # Create the basic testing environment
  # ------------------------------------
  # Explicitly add defaults channel, see https://github.com/conda/conda/issues/2675
  - >
    echo 'Configure conda and create an environment';
    conda config --set always_yes yes --set changeps1 no;
    conda config --set show_channel_urls True;
    conda config --add channels conda-forge;
    conda update --quiet conda;
    ENV_NAME='test-environment';
    conda create --quiet -n $ENV_NAME python=$TRAVIS_PYTHON_VERSION pip;
    source activate $ENV_NAME;
  # Customise the testing environment
  # ---------------------------------
  - >
    head -n 12 requirements.txt | sed -E -e 's/\[.*\]//g' >test-requirements.txt;
    conda install --quiet -n $ENV_NAME --file test-requirements.txt;
    pip install .[tests];
script:
  - python setup.py test
